"""Supabase_Production_v1

Revision ID: 021a3f9ea1f6
Revises: 
Create Date: 2026-06-23 01:33:24.197951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021a3f9ea1f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('analyst_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('total_wins', sa.Integer(), nullable=False),
    sa.Column('total_losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('average_pnl', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyst_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyst_profile_user_id'), ['user_id'], unique=True)
        batch_op.create_index('ix_analyst_total_trades', ['total_trades'], unique=False)
        batch_op.create_index('ix_analyst_win_rate', ['win_rate'], unique=False)

    op.create_table('live_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('stream_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'ENDED', name='roomstatus'), nullable=False),
    sa.Column('viewer_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_room_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_room_mentor_id'), ['mentor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_room_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_room_stream_key'), ['stream_key'], unique=True)

    op.create_table('social_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('prediction', sa.Enum('LONG', 'SHORT', name='predictiontype'), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'WON', 'LOST', 'CLOSED_EARLY', name='poststatus'), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_post_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_post_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_post_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_post_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_social_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_social_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('user_legal_consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('document_version', sa.String(length=20), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_legal_consent', schema=None) as batch_op:
        batch_op.create_index('ix_user_consent_user_timestamp', ['user_id', 'timestamp_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_legal_consent_document_hash'), ['document_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_legal_consent_document_version'), ['document_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_legal_consent_timestamp_utc'), ['timestamp_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_legal_consent_user_id'), ['user_id'], unique=False)

    op.create_table('room_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['live_room.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_room_message_room_created', ['room_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_message_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_message_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_room_message_room_id'))
        batch_op.drop_index('ix_room_message_room_created')
        batch_op.drop_index(batch_op.f('ix_room_message_created_at'))

    op.drop_table('room_message')
    with op.batch_alter_table('user_legal_consent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_legal_consent_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_legal_consent_timestamp_utc'))
        batch_op.drop_index(batch_op.f('ix_user_legal_consent_document_version'))
        batch_op.drop_index(batch_op.f('ix_user_legal_consent_document_hash'))
        batch_op.drop_index('ix_user_consent_user_timestamp')

    op.drop_table('user_legal_consent')
    with op.batch_alter_table('social_post', schema=None) as batch_op:
        batch_op.drop_index('ix_social_user_created')
        batch_op.drop_index('ix_social_status_created')
        batch_op.drop_index(batch_op.f('ix_social_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_social_post_symbol'))
        batch_op.drop_index(batch_op.f('ix_social_post_status'))
        batch_op.drop_index(batch_op.f('ix_social_post_created_at'))

    op.drop_table('social_post')
    with op.batch_alter_table('live_room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_room_stream_key'))
        batch_op.drop_index(batch_op.f('ix_live_room_status'))
        batch_op.drop_index(batch_op.f('ix_live_room_mentor_id'))
        batch_op.drop_index(batch_op.f('ix_live_room_created_at'))

    op.drop_table('live_room')
    with op.batch_alter_table('analyst_profile', schema=None) as batch_op:
        batch_op.drop_index('ix_analyst_win_rate')
        batch_op.drop_index('ix_analyst_total_trades')
        batch_op.drop_index(batch_op.f('ix_analyst_profile_user_id'))

    op.drop_table('analyst_profile')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
